import { Router } from 'express';
import { SLOT_MINUTES, generateSlots, parseSlotId } from '../slots.js';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Logic generated by AI Agent: booking creation guarded by a transaction plus a
// UNIQUE(start_time) constraint. Any concurrent double-booking attempt raises
// SQLITE_CONSTRAINT_UNIQUE, which is mapped to HTTP 409 Conflict with the exact
// message defined in api-contract.yaml.
export function bookingsRouter(db) {
  const router = Router();

  router.post('/', (req, res) => {
    const { slotId, name, email } = req.body ?? {};

    const parsed = parseSlotId(slotId);
    if (!parsed) {
      return res.status(400).json({
        error: 'slotId is missing or does not reference a valid slot.',
      });
    }

    if (typeof name !== 'string' || name.trim().length === 0) {
      return res.status(400).json({ error: 'name is required and must not be empty.' });
    }
    const cleanName = name.trim();

    let cleanEmail = null;
    if (email !== undefined && email !== null && email !== '') {
      if (typeof email !== 'string' || !EMAIL_RE.test(email.trim())) {
        return res.status(400).json({ error: 'email must be a valid email address.' });
      }
      cleanEmail = email.trim().toLowerCase();
    }

    const { date } = parsed;
    const schedule = generateSlots(date);
    const slot = schedule.find((item) => item.id === slotId);
    if (!slot) {
      return res.status(404).json({ error: 'The requested slot does not exist.' });
    }

    const start = new Date(slotId);
    if (start.getTime() < Date.now()) {
      return res.status(400).json({ error: 'This slot is in the past and cannot be booked.' });
    }
    const end = new Date(start.getTime() + SLOT_MINUTES * 60 * 1000);

    const createdAt = new Date().toISOString();
    const insert = db.prepare(`
      INSERT INTO bookings (slot_date, start_time, end_time, name, email, created_at)
      VALUES (?, ?, ?, ?, ?, ?)
    `);

    try {
      const info = db.transaction(() =>
        insert.run(date, slotId, end.toISOString(), cleanName, cleanEmail, createdAt),
      )();

      const booking = {
        id: String(info.lastInsertRowid),
        slotId,
        start: slotId,
        end: end.toISOString(),
        name: cleanName,
        email: cleanEmail,
        createdAt,
      };
      return res.status(201).json(booking);
    } catch (err) {
      if (err.code === 'SQLITE_CONSTRAINT_UNIQUE') {
        return res.status(409).json({ error: 'This time slot is already reserved.' });
      }
      throw err;
    }
  });

  router.get('/', (req, res) => {
    const rows = db
      .prepare(`
        SELECT id, start_time, end_time, name, email, created_at
        FROM bookings
        WHERE start_time >= ?
        ORDER BY start_time ASC
      `)
      .all(new Date().toISOString());

    const bookings = rows.map((row) => ({
      id: String(row.id),
      slotId: row.start_time,
      start: row.start_time,
      end: row.end_time,
      name: row.name,
      email: row.email,
      createdAt: row.created_at,
    }));

    return res.json(bookings);
  });

  return router;
}
