import { Router } from 'express';
import { generateSlots, isValidDateString } from '../slots.js';

// Logic generated by AI Agent: timezone-free slot generation and availability
// lookup driven by the booked start times persisted in the bookings table.
export function slotsRouter(db) {
  const router = Router();

  router.get('/', (req, res) => {
    const { date } = req.query;

    if (!isValidDateString(date)) {
      return res.status(400).json({
        error: 'The date parameter must be a valid calendar date in YYYY-MM-DD format.',
      });
    }

    const bookedStarts = db
      .prepare('SELECT start_time FROM bookings WHERE slot_date = ?')
      .all(date)
      .map((row) => row.start_time);

    const nowIso = new Date().toISOString();
    const slots = generateSlots(date, bookedStarts).filter(
      (slot) => slot.start >= nowIso,
    );

    return res.json({ date, slots });
  });

  return router;
}
