import { useState } from 'react';
import { createBooking } from '../api.js';

function formatRange(slot) {
  const start = new Date(slot.start);
  const end = new Date(slot.end);
  const options = { weekday: 'long', day: 'numeric', month: 'long' };
  return `${start.toLocaleDateString([], options)} · ${start.toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
  })} – ${end.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
}

export default function BookingModal({ slot, onClose, onBooked }) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (submitting) return;
    setSubmitting(true);
    setError(null);
    try {
      const payload = { slotId: slot.id, name: name.trim() };
      if (email.trim()) {
        payload.email = email.trim();
      }
      await createBooking(payload);
      onBooked(`Booked! See you at ${new Date(slot.start).toLocaleTimeString([], {
        hour: '2-digit',
        minute: '2-digit',
      })}.`, 'success');
    } catch (err) {
      // Logic generated by AI Agent: a 409 from the API means the slot was
      // taken while the guest was filling the form, so we surface a friendly
      // message and refresh the availability.
      if (err.status === 409) {
        onBooked('This time slot is already reserved. Please pick another one.', 'error');
      } else {
        setError(err.message);
      }
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" role="dialog" aria-modal="true" onClick={(e) => e.stopPropagation()}>
        <h2>Book your call</h2>
        <p className="muted">{formatRange(slot)}</p>

        {error && <div className="alert">{error}</div>}

        <form onSubmit={handleSubmit}>
          <label className="field">
            <span>Your name</span>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Ada Lovelace"
              required
              autoFocus
            />
          </label>
          <label className="field">
            <span>Email <small>(optional)</small></span>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
            />
          </label>

          <div className="modal-actions">
            <button type="button" className="button ghost" onClick={onClose}>
              Cancel
            </button>
            <button type="submit" className="button primary" disabled={submitting}>
              {submitting ? 'Booking…' : 'Confirm booking'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
